# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c93e457e8a2d10d5f4316d73f961c468b191afe5439496eb2c0f7b270eda75f4a8eb0e58718fb0bfe52351f7ec46bc0b874e1b9fd8bf4773e57d1ffa92edbb

test:
  secret_key_base: 026d7e004221036c0654c89fc6461f1832bbd6f44b9e7ccdd73dcda80f1dd5974d5260f46796c57bea14c67bc0473a82b236652a74c1119eb6222c6278640e08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
